### PR TITLE
fix: ssim is not commutative for masked arrays

### PR DESCRIPTION
**Pull request by roelofvandijkO**
https://git.gfz-potsdam.de/danschef/arosics/-/issues/113

### CODE REVIEW

**Comment by danschef** [comment]
Any reason for closing this PR together with #45 and #46? So far, I had no time to look into this but until next work, this should be possible.

**Comment by roelofvandijkO** [comment]
Yes. You are tracking them in Gitlab (issues), you can reopen them again here if needed, and they clog up my PR view in Github. Hope that's OK?

**Comment by danschef** [comment]
Ok fine.

**Comment by roelofvandijkO** [comment]
Mach ich!

**Pull request closed without merging**
